{% set name = "apache-airflow-providers-mongo" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-mongo-{{ version }}.tar.gz
  sha256: 8287c15f54ec63cf7833c16f11a23f00a3deeca5a4eeaa3a452ceb52124d8880

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - wheel
  run:
    - apache-airflow >=2.1.0
    - dnspython >=1.13.0,<3.0.0
    - pymongo >=3.6.0
    - python >=3.6

test:
  imports:
    - airflow.providers.mongo
    - airflow.providers.mongo.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for MongoDB for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-mongo/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
